### hola server
GET http://localhost:3000


### recupera todos los actores
GET http://localhost:3000/actores


### recupera un actor por id
GET http://localhost:3000/actores/124




### crea un nuevo actor
POST http://localhost:3000/actores
Content-Type: application/json

{
  "nombre": "Pepe",
  "apellido": "Lui"
}









### recupera todos los contenidos
GET http://localhost:3000/contenidos

















## actualiza un actor por id
PUT http://localhost:3000/actores/:id
Content-Type: application/json

{

}

## elimina un actor por id
DELETE http://localhost:3000/actores/:id





## recupera una pelicula por id
GET http://localhost:3000/peliculas/:id


## crea una nueva pelicula
POST http://localhost:3000/peliculas
Content-Type: application/json

{

}


## actualiza una pelicula por id
PUT http://localhost:3000/peliculas/:id
Content-Type: application/json

{}


## elimina una pelicula por id
DELETE http://localhost:3000/peliculas/:id

